include:
  remote: 'https://github.com/git-developer/solarview-base/raw/v1.6.0/.gitlab-ci.yml'

variables:
  DOCKERFILE_URL: 'https://github.com/git-developer/solarview-base/raw/v1.6.0/Dockerfile'
  BUILD_ARGS: 'APP_NAME=kaco-fb'
  IMAGE_TITLE: 'SolarView KACO-Proxy'
  UPDATE_CHECK_URLS: 'http://www.solarview.info/downloads/kaco-fb.zip'
